### ISSUE TITLE
CustomItems.yml resets itself if there's a typo in the file.

### ISSUE THREAD

**Issue by solo64** [PixelOutlaw/MythicDrops#245]
Let's say I make a sword called 'Azure Fury' in customItems.yml. If I accidentally quote it just like this:

displayName: 'Azure Fury"

The whole file will reset itself back to default once I've reloaded the configs. This is very annoying in that I have to add in all my custom items again after the fact and hope I don't make any more mistakes in the file. Although the reset makes a backup file, it's blank and it gets erased just the same.

Is there a method of reliably backing up my custom items in-game? Right now, I'm keeping a manual copy of the configs in case I mess up and erase the file again, but I'd prefer if there was a command that could copy the exact state of my config in-game and reload it in the event of a catastrophe.

Edit: Found out it's not only limited to the one file, but also the language.yml file, too.

**Comment by asheneff** [comment]
it especially dislikes whenever you use an apostraphe ( ' ) in lore (for obvious reasons) and when there is no space after an elipsis ( ... ).
