### ISSUE TITLE
Trouble Adding Mod Items

### ISSUE THREAD

**Issue by VelikiySvet** [PixelOutlaw/MythicDrops#259]
I've installed Balkon's Weapons on my cauldron server and I've edited the language, tier, and groups files to include the balkon weapon ids (4096-4152). However, the items don't spawn in when I use the /md spawn command. I've tried using using the item ids, the ids inside of 'id' and their word ids SPEAR.WOOD and SPEAR_WOOD but nothing I've tried has worked. The tutorial video is a little out of date on how to get this to work. How can I get it to work?

**Comment by Drehverschluss** [comment]
you need to write a new section inside the "itemGroups.yml"

I made it for the CustomNPC armors like this.

    WizardArmor:
    - CUSTOMNPCS_NPCWIZARDHEAD
    - CUSTOMNPCS_NPCWIZARDCHEST
    - CUSTOMNPCS_NPCWIZARDPANTS
    CommonHeadsFeather:
    - CUSTOMNPCS_NPCWIZARDHEAD
    - TCONSTRUCT_HELMETWOOD
    - LEATHER_HELMET
    - CUSTOMNPCS_NPCFULLWOODENHEAD
    - CUSTOMNPCS_NPCCOWLEATHERHEAD
    CommonHeadsLight:
    - GOLDEN_HELMET
    - CHAINMAIL_HELMET
    - CUSTOMNPCS_NPCNINJAHEAD
    - CUSTOMNPCS_NPCCOMMISSARHEAD
    - CUSTOMNPCS_NPCBANDITMASK
    CommonHeadsMedium:
    - IRON_HELMET
    - CUSTOMNPCS_NPCSOLDIERHEAD
    - CUSTOMNPCS_NPCNANORUMHEAD
    - CUSTOMNPCS_NPCASSASSINHEAD
    CommonHeadsHeavy:
    - DIAMOND_HELMET
    - CUSTOMNPCS_NPCMITHRILHEAD
    - CUSTOMNPCS_NPCDEMONICHEAD
    - CUSTOMNPCS_NPCX407HEAD


And Than you go into your desiered Tier.yml and add to the drops section smething like this.
```
itemTypes:
  allowedGroups:
  - CommonHeadsFeather
```

Hope this helps you.
