### ISSUE TITLE
Next Feature Request :)

### ISSUE THREAD

**Issue by Drehverschluss** [PixelOutlaw/MythicDrops#264]
This time its about the Identifie Tomes.

Did you made thougt about a more "Diablo" way? 
What i mean are stackable Tomes. Or at least a Item wich called Foliant where you can Stack your found tomes. This Foliant will have a simple counter in the lore and work as a Identifie Tome. At least there are some in.

MFG

**Comment by Drehverschluss** [comment]
Some news? :)

**Comment by Nunnery** [comment]
I think this would be cool. I'll definitely consider it, along with socket extenders, for the next version increment.

**Comment by Drehverschluss** [comment]
awesome!
