### ISSUE TITLE
Commented configuration files

### ISSUE THREAD

**Issue by charliebritton** [PixelOutlaw/MythicDrops#270]
I have found that is very useful for the developer to release a configuration file that has lots of comments explaining what everything does, and seeing as there is not really any plugin wiki anywhere, it would be nice for you to release a config with annotations.

**Comment by Zendrex** [comment]
@Nunnery Any progress on documentation?

I wouldn't mind writing a wiki for the plugin, however would need you to explain it to me. Things like MythicMobs integration, how zones work, etc have no information it and thus puts a lot of people in the dark about what to do.

**Comment by Nunnery** [comment]
I haven't had an opportunity to begin working on documentation. It'll most likely be a while before I can do so.

If you really want to work on it, the wiki should be publicly editable and you can add information as you come across it.
