### ISSUE TITLE
Invalid book tag

### ISSUE THREAD

**Issue by doitliketyler** [PixelOutlaw/MythicDrops#272]
Hello again. I've ran into a bug I can't figure out. The custom book items being dropped from the mobs are showing "Invalid book tag" instead of the written text. The books are signed properly too. Any ideas whats happening here?

**Comment by Nunnery** [comment]
It would most likely be an issue with the BookMeta object... Can you provide me with a copy of your customItems.yml and a screenshot of the issue?

**Comment by doitliketyler** [comment]
Oh weird. I apologize for the extremely late response. I didn't get an email notification that you had responded.

Screenshot: https://imgur.com/eSiu2JK
customItems.yml: http://pastebin.com/AWWvH0zu

The first thing I thought was that the "null" in front of the author name was the cause but even after I removed it it was still happening.
