### ISSUE TITLE
Enchant levels go way above what is in config

### ISSUE THREAD

**Issue by Naskel-CastiaMC** [PixelOutlaw/MythicDrops#285]
Hello

I'm using the latest version of MythicDrops (4.0.9-a1188cb) on Spigot 1.9.4 and I'm having issues with my drops.
Some drops have extremely high enchants even though we've set the cap to be level 10 in our config. I've items like this http://prnt.sc/b9z2vf isn't suppposed to happen. Our runic tier is even set to have 2-6 enchants.

I think it's adding together same enchant multiple times but I'm not sure.

Thank you,
Naskel

**Comment by Nunnery** [comment]
Try running the build located here: [TealCube Jenkins](http://build.tealcubegames.com/job/MythicDrops/branch/development/)
