### ISSUE TITLE
Dye

### ISSUE THREAD

**Issue by Scratch741** [PixelOutlaw/MythicDrops#293]
Is there a way to make a dye as an item? For example I want to do Rose Red, but it seems impossible because I have tried several material names, for example: INK_SACK:1, ROSE_RED etc.

**Comment by Nunnery** [comment]
It isn't currently possible, in part due to how Bukkit/Spigot have discontinued real support for that kind of item metadata. I could readd that support, but it becomes difficult to maintain.
