### ISSUE TITLE
Trying to modify custom items

### ISSUE THREAD

**Issue by Maegliin** [PixelOutlaw/MythicDrops#299]
Topple,

As you suggested, I am including the info here.  I am very new to this, and am probably missing the bleeding obvious.
[customItems.yml.txt](https://github.com/Nunnery/MythicDrops/files/520208/customItems.yml.txt)

**Comment by Maegliin** [comment]
[debug.log.txt](https://github.com/Nunnery/MythicDrops/files/520211/debug.log.txt)

**Comment by Nunnery** [comment]
According to this, it's loading all of the custom items. When you run "/md custom -c socketswordstone -a 1", what is the output?

**Comment by Maegliin** [comment]
A socketswordstone... so I have a zombie spawner room set up to test drops...  I'll see something carrying an item.  Say a diamond axe, but when it drops it, it poofs.  this happens with all items.  Diamond axe is the most obvious.  Or e.g. I've got x2 the spawn rate on a leather_chestplate, versus a diamond sword.  I've gotten 1 chest, but like 5 diamond swords, even though it is weighted double.  Or if I bump up the  weight on wooden swords to make them the most common by far, I only seem to get them and nothing else.

**Comment by Nunnery** [comment]
Can you post the other configuration files (creatureSpawning.yml and config.yml) using HasteBin?

**Comment by Maegliin** [comment]
http://hastebin.com/idadigasok.css

http://hastebin.com/volocakako.lua

**Comment by Nunnery** [comment]
One issue that you might be seeing is that Minecraft will occasionally spawn mobs with items by default. You can override this by turning on blank-mob-spawns in your config.yml.
