### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Namnodorel** [PixelOutlaw/MythicDrops#306]
MythicDrops is a really, _really_ awesome plugin. It is complex, yes, but due to this there are just *so* many features, it's all I'd have ever wanted from a plugin like this. Except - that there is a horrible lack of documentation fo MythicDrops. Especially complex plugins like MythicDrops need to be well documented, but i was unable to find anything up-to-date which explains the config. Yes, you can learn many things by just looking at the default config, but it doesn't explain everything. For example, I'd like to know, what exactly the bonusLore is, and when it is applied. What are optimalDistance and maximalDistance? And I could go on. MythicDrops needs a good documentation of the config. Really.

**Comment by GershonR** [comment]
Agree this needs documentation there is nowhere to explain what things are or what they mean or do

**Comment by CakeLady** [comment]
Agreed!
