### ISSUE TITLE
Mobs that pick up MythicDrops dupe the Drop

### ISSUE THREAD

**Issue by MonoLime** [PixelOutlaw/MythicDrops#307]
When a Mob picks up any generic MythicDrop item, such as a Zombie or Skeleton. It will drop 2 copies of that MythicDrop item on death. I believe this has something to do with a conflict MythicDrops randomization of drops. 

Suggestion: Prevent MythicDrops from dropping an extra item when the Mob has picked one up already
or Prevent Mob pickup when MythicDrops plugin is active.

**Comment by SirKillian** [comment]
Sorry for very very late bump, After updating to 1.12 last week, this issue started to happen on my server as well.

**Comment by Nunnery** [comment]
There's a config option you can change that will prevent mobs from picking up items.
