### ISSUE TITLE
Adding Strength/AttackDamage to socket gems

### ISSUE THREAD

**Issue by nitrostam22** [PixelOutlaw/MythicDrops#325]
I have been attempting to increase the damage of weapons by creating Socket gems with damage(strength) EX: strength or Attack Damage. I need to add around 100,000 attack damage (roughly) or enough to add 300 ish raw damage.

  The issue is I am unable to apply any form of strength to a socket gem. I seem to be able to apply most other effects, for instance speed at a level of 100,000 (creates intense lag but for testing purposes does work)
 I have tried dozens of variation of the syntax Attack_Damage and Strength. This leads me to believe there may be an issue with gems directly applying damage to the player/item/wepon

  I have tried adding it as an enchantment effect as well instead of a potion effect, this still does not work

**Comment by Nunnery** [comment]
MythicDrops doesn't support adding attributes to items. We support adding potion effects via socket gems.  We also support adding enchantments.

Potion effect names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
Enchantment names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html

**Comment by milkmoron** [comment]
Look for LoreAttributesRecoded or ItemLoreStats. LoreAttributesRecoded is much simpler.
