### ISSUE TITLE
Mythicdrops file not working

### ISSUE THREAD

**Issue by dtkach12** [PixelOutlaw/MythicDrops#334]
Been trying to figure out how to add sockets and enchants to custom items, and I have encountered a few errors, first of all, it seems only the item last added to the CustomItems.yml actually spawns ingame, and I have tried editing everything, even included the enchant and socket-code from the tiers onto the items, to no avail.

**Comment by Nunnery** [comment]
Please use PasteBin or HasteBin or some other snippet site to share your customItems.yml.
