### ISSUE TITLE
Socketgem does not work:

### ISSUE THREAD

**Issue by Serpano** [PixelOutlaw/MythicDrops#343]
Hello Anybody i have a Problem With Mythicdrops i using Spigot 1.12 + Java 8 and a few more Plugings see here:

Plugins (15): OpenTerrainGenerator, MythicDrops, WorldEdit, LoreAttributesRecoded, Essentials, EssentialsProtect, EssentialsChat, GroupManager, AgarthaLib, EssentialsAntiBuild, BlockRegen, LifeEssence, ConquestiaMobs, EssentialsSpawn, LiveCompass

So my problem: when i use the command /md gem it spawns a gem that is correct
so i have a armor with sockets see pictures you can see the problem also:

http://www.bilder-upload.eu/show.php?file=ed1c8e-1517719678.png <- Armor with sockets

http://www.bilder-upload.eu/show.php?file=a6ae9b-1517719643.png <--- Socketgem

http://www.bilder-upload.eu/show.php?file=724807-1517719417.png <- Error

So i describe it when i click right with the gem i should display the green message not both
I hope you can recognize the problem.

i cannot use the socketgem but why?
Please help:

**Comment by Piperrainfield** [comment]
Try right clicking in the air. It did the same for me, but when I did it in the air, with nothing in front of me, it worked perfectly.
