### ISSUE TITLE
WARN SLF4J: Failed to load class

### ISSUE THREAD

**Issue by SirGoldman-git** [PixelOutlaw/MythicDrops#348]
> 27.04 14:55:40 [Server] INFO [MythicDrops] Enabling MythicDrops v4.1.2-bd6c06f
> 27.04 14:55:40 [Server] WARN SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> 27.04 14:55:40 [Server] WARN SLF4J: Defaulting to no-operation (NOP) logger implementation
> 27.04 14:55:40 [Server] WARN SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> 27.04 14:55:40 [Server] INFO [MythicDrops] Loading tiers from /tiers/
> 27.04 14:55:40 [Server] INFO [MythicDrops] AuraRunnable disabled due to no gems detected as using AURA target type.
> 27.04 14:55:40 [Server] INFO [MythicDrops] Mobs spawning with equipment enabled
> 27.04 14:55:40 [Server] INFO [MythicDrops] Repairing enabled
> 27.04 14:55:40 [Server] INFO [MythicDrops] Socketting enabled

This error is only on boot, not sure what the issue is.

**Comment by SirGoldman-git** [comment]
Spigot: 1.12.2 MD: 4.1.2 Jave: 8 171

**Comment by SirGoldman-git** [comment]
Still getting this error on boot.

**Comment by Nunnery** [comment]
@SirGoldman-git - As of 4.2.0?

**Comment by SirGoldman-git** [comment]
Yes, last version of spigot. Everything works 100% fine, just every boot I get that error.
