### ISSUE TITLE
Custom Items

### ISSUE THREAD

**Issue by CACGaming** [PixelOutlaw/MythicDrops#350]
So I use MythicDrops on my server and am trying to make custom items but I can't figure out if there is a way to have affects or stuff of the sort. For example I have an item called 'Talisman of Health'.
/give @p emerald 1 0 {
    display: {
        Name: "Talisman of Health",
        Lore: [
            "+20 Health"
        ]
    },
    AttributeModifiers: [
        {
            AttributeName: "generic.maxHealth",
            Name: "generic.maxHealth",
            Amount: 20,
            Operation: 0,
            UUIDMost: 83581,
            UUIDLeast: 627690
        }
    ],
    HideFlags: 2
}

when I use /md customcreate 1 1 it makes the item but does not keep the health boost

**Comment by Nunnery** [comment]
Attributes are not currently supported by MythicDrops due to no native Spigot/Bukkit API for interacting with attributes.
