### ISSUE TITLE
Mythic Drops - Some tiers not dropping with 100% chance.

### ISSUE THREAD

**Issue by YDGTV** [PixelOutlaw/MythicDrops#359]
So with Mythic Drops, I am having issues with mobs dropping items of a desired tier and I can't figure out why they are not dropping it. I have set all of the drop rates to a 100% on a monster death and enabled all the tiers to drop off every mob, but for certain tiers, the loot is not dropping.
But for some others, It is dropping.
(Some other tiers)
I have my world name set in the config, but it still isn't working
I have a tier called Common. In the common tier, I have it so mobs spawn with the drop with 100% drop chance on death. In my server, I see the mobs spawn with the Common tier but they do not drop the item in their hand. This is the same thing for my uncommon tier as well.
On the other hand, I have another tier called Rare. In the rare tier, I have the same properties set from the common tier but these drops do in fact drop on a mob death. This is the same scenario with the exotic and legendary tiers as well.

**Comment by Nunnery** [comment]
Can you post the contents of your common.yml and your uncommon.yml?

**Comment by Nunnery** [comment]
I think this is related to PaperMC/Paper#1484.

**Comment by Nunnery** [comment]
Others are reporting it solved in the discord.
