### ISSUE TITLE
Socket limits incorrect

### ISSUE THREAD

**Issue by BurntValentine** [PixelOutlaw/MythicDrops#372]
Using the 5.1.0 release candidate posted on the Discord with Spigot 1.13.2 - having set Common and Uncommon to have 0 min/max sockets I am still getting a socket slot on most if not all of my Common/Uncommon drops

Switching back to the latest 5.0.0 release on SpigotMC stops them dropping with socket slots again!

**Comment by BurntValentine** [comment]
Ahh to be more specific it's not giving them a socket, but while they don't have a socket it's still putting the socket lore on the item (the "find a socket gem" bit)

**Comment by Nunnery** [comment]
Ah, I see where this is occurring. I will have a fix for this in 5.1.1.

**Comment by BurntValentine** [comment]
Awesome - thank you!
