### ISSUE TITLE
"can-drop-socket-gems-on-items" not working

### ISSUE THREAD

**Issue by BurntValentine** [PixelOutlaw/MythicDrops#374]
5.0.1 release candidate from Discord, Spigot 1.13.2

Enabling the "can-drop-socket-gems-on-items" option in the socketting file doesn't appear to do anything - I assume this is intended to mean you can drag and drop the socket gem item in your inventory onto an item with a free socket to use it but it doesn't do anything enabled or not (same for dropping the items together if that's how it's meant to work, but I assume not)

**Comment by Nunnery** [comment]
That is how it's intended to work, but that field isn't actually used anywhere. I'm not entirely sure when I'll get to making the field actually used, but you're absolutely right.

**Comment by BurntValentine** [comment]
Hmm, would be a nice feature to have working (if the right click event with the gem in hand could be disabled alongside it, as per my other post, so it doesn't still give the chat messages about right click with the gem then the item etc..) as I was going to have the gem item as a Conduit as they look like something that should be slotted into things, but they're a placeable item. I can disable the placing via a skript etc.. but the messages are still given.

Not a massive issue if not - I can use an emerald or an iron nugget etc... that can't be placed if need be!
