### ISSUE TITLE
Custom Socket Names Not Working

### ISSUE THREAD

**Issue by BurntValentine** [PixelOutlaw/MythicDrops#375]
5.0.1 release candidate from the Discord, Spigot 1.13.2

Editing the socket-name in the socketting file stops the socket gems from working at all.

For example if I have it set to `&5Power Gem - &6%socketgem%` it works fine, however if I even change it just to`&5Power Gem &7- &6%socketgem%` the gems no longer do anything.

Ideally I'd like to be able to have custom symbols in it as well, such as having it as `&6✧ &5Power Gem &6✧ &7-- &d%socketgem%` due to having item drop names visible - the plugin parses the symbol fine and the item is given with the symbol, but as above due to the altered name it does nothing.

**Comment by Nunnery** [comment]
Just a quick check, are you spawning a socket gem with the name format `&5Power Gem - &6%socketgem%`, then changing the `socket-name` field, and then the socket gem you spawned isn't working? Or is it

1. Spawn socket gem with name format `&5Power Gem - &6%socketgem%`
2. Use socket gem successfully
3. Change `socket-name` field and restart server
4. Spawn socket gem with name format `&5Power Gem &7- &6%socketgem%`
5. Socket gem doesn't work

**Comment by BurntValentine** [comment]
It's as you step-by-stepped it - set it up with the socket gem name formatted as `&5Power Gem - &6%socketgem%`, restarted and spawned one in and it works fine.

Edited the socket gem name in the files to `&5Power Gem &7- &6%socketgem%` (or any other variation that adds extra colours or symbols beyond a colour at the start and before the socket gem name variable as far as I can tell) and then save changes and restart, then spawn a new gem in and it does nothing (I did both a server restart and an `/md reload` to see if it made any difference, does it either way)

**Comment by Nunnery** [comment]
I have found the place where the issue is being caused - it's a bit of a weird one. I'll have this fixed for 5.1.1 as well.

**Comment by BurntValentine** [comment]
Awesome - thank you!
