### ISSUE TITLE
min/maxBonusEnchantments not working

### ISSUE THREAD

**Issue by BurntValentine** [PixelOutlaw/MythicDrops#377]
Setting the minimumBonusEnchantments option does not appear to work - for example I have the Legendary tier set to:

  minimumBonusEnchantments: 4
  maximumBonusEnchantments: 7

But if I spawn in a load of Legendary tier items the majority of them are 0-3 enchants

**Comment by BurntValentine** [comment]
To confirm I have all enchants (minus a few negatives like the curses) set in the bonus enchants section, the only one I have as a base enchant is Loyalty

This is with the latest release of MD (5.1.2) and Spigot 1.13.2

**Comment by Nunnery** [comment]
Do you have safeBonusEnchantments turned on?

**Comment by BurntValentine** [comment]
Yes, I have safeBonusEnchantments turned on - but logically if that's on (which is pretty much necessary on high tiers so you don't get a mega rare drop with enchants that are useless on it) it should go through every enchant in the list before stopping, so if the minimum is set to 4 and there are 4 available enchants that can all safely go on the item in Vanilla with each other, they should all be put on - only when there are less than 4 enchants that can go together on that specific item in Vanilla should there be less than 4 enchants.

For example - this is my current legendary tier file: https://gist.github.com/BurntValentine/aca01833b791ab3814e3eff351e7fba5

But when I spawn a load of legendary tier items in multiple have less than 4 enchants on them but there are other enchants it could have used. For example I received a diamond pickaxe, legendary tier, with just unbreaking and silk touch - unbreaking is expected, but then there should be up to 4 extras and it could have added efficiency but it skipped over it, and had a diamond sword spawned in with unbreaking and sharpness but it could have had sweeping edge, fire aspect, looting and knockback added

**Comment by Nunnery** [comment]
You're right that's how it should logically follow, but that's unfortunately not how it's currently implemented. I'll fix it up here for 5.2.0.

**Comment by BurntValentine** [comment]
Thank you!

**Comment by Nunnery** [comment]
Long story short, here's how the bonus enchantment setup will work now:

We get the list of bonus enchantments from the tier and filter out any invalid enchantments. We then determine if safe bonus enchantments are turned on and, if it is on, filter out any unsafe enchantments. We then determine how many enchantments to add by picking a random number between minBonusEnchantments (inclusive) and maxBonusEnchantments (inclusive). We then iterate that many times, attempting to add enchantments from the list by generating a random level for the enchantment and adding it to the item. If we attempt to add an enchantment that is already there, we combine them, respecting the minimum and maximum levels of the enchantment in the config. If we don't allow high bonus enchantments, we then clamp the level back down to safe levels.
