### ISSUE TITLE
Need versions for 1.5.2/1.6.4/1.7.10/1.12.2/1.13.2

### ISSUE THREAD

**Issue by Zilacon** [PixelOutlaw/MythicDrops#414]
Hey @ToppleTheNun long time no see. Havent talked to you since you were working on DiabloDrops with Death_Marine. Anyways im looking to throw this plugin on my network of 14 servers and am looking for the older versions of it.

Thanks.

**Comment by UltraFaceguy** [comment]
Hey @ToppleTheNun long time no see. Haven't talked to you since you were working on DiabloDrops with Death_Marine. Anyways I'm looking up throw this plugin on my network of 69 servers and I'm looking for unspecified older versions of it, by making a GitHub issue.

Thanks.

**Comment by Zilacon** [comment]
I dont know what your problem is, but there is no place to download older versions of the plugin. The only page i can find is on dev bukkit of the same name with only one file from 2012.

Github is where you post issues for the plugin or project, guess what? Not finding older versions for a plugin is a issue. So this is the correct place to post that issue.

**Comment by Nunnery** [comment]
You can find a history of the versions of the plugin for download here: https://www.spigotmc.org/resources/mythicdrops.6114/history

Unfortunately, it doesn't have the direct Minecraft version associated with it. Additionally, the git history for the plugin only has support back until 1.8.7 of Minecraft, though I'm sure some of the earlier binaries on Spigot support more than that. You can typically open the tag associated with the version (e.g., https://github.com/PixelOutlaw/MythicDrops/tree/mythicdrops-4.0.5), open the pom.xml in the repository, and search for Bukkit to find the version of Minecraft that that version supports.

**Comment by Zilacon** [comment]
Darn, thanks for replying. Im looking for your older versions. Guess i cant use it.
