### ISSUE TITLE
Suggestion socket combiners.

### ISSUE THREAD

**Issue by jordanwilliams1** [PixelOutlaw/MythicDrops#427]
Could you allow "/mythicdrops combiners add" to be put on any block? I Want to make some sort of nice build but a chest doesn't look very appealing.

Or be able to open the gui from a runnable command? People could hook it into a CommandNPC (Right click a npc and it runs a command for you)

It would also be cool if you could add an option where it requires a "custom item" as payment to combine all the sockets, This could be pretty cool? 

I'd also like to edit the name of the gui/name on the iron_bars. 

Also these could be configurable options which just adds more to the plugin. It will enchant players experiences :)

**Comment by jordanwilliams1** [comment]
New setup if command is added 😄 
![image](https://user-images.githubusercontent.com/16514150/71320241-57862d80-24a0-11ea-96b9-8c9ebcec00c6.png)



Current Setup 😢 
![image](https://user-images.githubusercontent.com/16514150/71320242-59e88780-24a0-11ea-95d9-253179d87e4d.png)

**Comment by ToppleTheNun** [comment]
The way that it's currently setup is to check if it's a socket gem combiner on inventory open and most blocks do not have inventories. I suppose I could change it to be on block interact and if the block is in the configured list, open an inventory instead of what it's doing now.

**Comment by ToppleTheNun** [comment]
Closing this as I've implemented the opening via command and you can already change the name and material type of the buffer (the iron bars).
