### ISSUE TITLE
Gem Lore 

### ISSUE THREAD

**Issue by BobbyMere** [PixelOutlaw/MythicDrops#477]
is there a way to not use this format? https://imgur.com/ZsKa5HZ
is there a way to just use the %type% variable and cut out all of the gem combiner function?
<img width="193" alt="Annotation 2020-07-18 050008" src="https://user-images.githubusercontent.com/25316276/87851403-f8fe2200-c8bd-11ea-9ed4-b3d5532e3fe6.png">

Would you be willing to add the variable %type% to this section here 
```    
socket-gem:
    glow: true
    name: '&3A&fu&bg&3m&fe&bn&3t&8 - &3%socketgem%'
    lore:
    - '&8&m-------------------'
    - '&F%type%'
    - '&8&m-------------------'
    - ''
    - '&8See &7/augments &8for'
    - '&8information about'
    - '&8augment infusion'

**Comment by ToppleTheNun** [comment]
Fixed in https://github.com/PixelOutlaw/MythicDrops/commit/06dc1d45f756e6cc79f2bfad4de51593a0ec3f31.
