### ISSUE TITLE
Request: Custom Head Support 

### ISSUE THREAD

**Issue by BobbyMere** [PixelOutlaw/MythicDrops#491]
I'm requesting support for custom heads but not specifically UUID, but rather item value like this
```eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODcxOWYyOGE2NzE5YmMzZGMwMDAzMDJhMTBmYTg3ZWM1NTc1MGQ1OGUyZDMyNjYzOTcwZjg5OWNhZDEyNGU0YyJ9fX0=```

Found [here](https://minecraft-heads.com/custom-heads/plants/39610-tropical-fruitl) or alternatively support for [this](https://www.spigotmc.org/resources/head-database.14280/) plugin

**Comment by ToppleTheNun** [comment]
Done in the latest build uploaded to the #builds channel. I can't test it myself, so you'll need to test it for me.

**Comment by ToppleTheNun** [comment]
Calling it done for now, open a new ticket if it's not working.
