### ISSUE TITLE
"broadcast-on-find" in customitems.yml only broadcasts to players in same world.

### ISSUE THREAD

**Issue by SirKillian** [PixelOutlaw/MythicDrops#493]
When having the setting "broadcast-on-find" set to true on items inside the customItems.yml and a player finds said item. It will only broadcast to all the players that are in the same world and not to all players online.

Not 100% sure if this is intentional or not. However, it would be nice it was broadcasted to the entire server and not exclusive to players in the same world.

**Comment by BobbyMere** [comment]
If this is indeed a bug, it dates back to at least 1.12. Could you keep an option for how it functions now; only broadcasts to people in the same world?
